services:
  postgres:
    image: postgres:15
    container_name: tradingplatform-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tradingplatform
      POSTGRES_PASSWORD: tradingplatform
      POSTGRES_DB: TradingPlatform
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:3.7.0
    container_name: tradingplatform-kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: tradingplatform-kafdrop
    ports:
      - "19000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9094
    depends_on:
      - kafka

volumes:
  postgres_data:
